### ISSUE TITLE
Investigate SSH Keys for Load Balancer Authentication 

### ISSUE THREAD

**Issue by aaranmcguire** [AshleyPoole/iControlLBO#2]
Look to see if Posh SSH supports SSH Keys and how best to implement this feature. If this is unsupported we need to find a way to cleanly allow users to create scripts that would allow the password to be obscured/encrypted.

**Comment by mynamewastaken** [comment]
After (an admittedly brief) glance at posh-ssh, it doesn't look like it. There's posh-git which will install the ssh binary (and also take care of ssh-agent for you). Might be a useful alternative.

**Comment by aaranmcguire** [comment]
It is supported, https://github.com/darkoperator/Posh-SSH/blob/691763cfefe3f2bf0b7c982d2002216f07a6e224/PoshSSH/PoshSSH/NewSSHSession.cs#L134 I just don't know how it should be used in the command.. I think you've got to use `KeyFile` in the command.

Let me know if you get it working and we can put it in the LB script.

**Comment by mynamewastaken** [comment]
Neat. As far as the private key goes - you can encrypt it at any time with a passphrase. At that point for our needs it should be good enough.

I'm looking into using a key now.

@aaranmcguire @AshleyPoole

**Comment by aaranmcguire** [comment]
Thanks @mynamewastaken for doing this.
